@startuml 
actor Tester as test
participant "Usuario" as usuario
participant "Producto" as producto
participant "Transaccion" as transaccion

test -> usuario : instanciar usuario("Juan")
test -> producto : instanciar producto("Producto 1")
test -> usuario : set balance = 200
test -> transaccion : instanciar transaccion(usuario, producto)
transaccion -> usuario : verificar balance
transaccion -> usuario : balance -= precio
test -> transaccion : verificar éxito
@enduml