@startuml Componentes

package "Frontend App" {
  [HTML/CSS]
  [JavaScript]
}

package "Backend Server" {
  [Flask App]
  [Database]
}

database "SQLite" {
  folder "Models" {
    [UsuarioModel]
    [ProductoModel]
    [TransaccionModel]
  }
}

[HTML/CSS] ..> [JavaScript] : Includes
[JavaScript] ..> [Flask App] : AJAX Requests
[Flask App] ..> [Database] : ORM
[Database] ..> [SQLite] : Uses

@enduml